/********************************************************************
* src/dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledict();
extern void G__cpp_setup_inheritancedict();
extern void G__cpp_setup_typetabledict();
extern void G__cpp_setup_memvardict();
extern void G__cpp_setup_globaldict();
extern void G__cpp_setup_memfuncdict();
extern void G__cpp_setup_funcdict();
extern void G__set_cpp_environmentdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "HGCSSSimHit.hh"
#include "HGCSSRecoHit.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictLN_TClass;
extern G__linked_taginfo G__dictLN_TBuffer;
extern G__linked_taginfo G__dictLN_TMemberInspector;
extern G__linked_taginfo G__dictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_G4SiHit;
extern G__linked_taginfo G__dictLN_vectorlEG4SiHitcOallocatorlEG4SiHitgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEG4SiHitcOallocatorlEG4SiHitgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_HGCSSSimHit;
extern G__linked_taginfo G__dictLN_vectorlEHGCSSSimHitcOallocatorlEHGCSSSimHitgRsPgR;
extern G__linked_taginfo G__dictLN_vectorlEHGCSSSimHitcOallocatorlEHGCSSSimHitgRsPgRcLcLiterator;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEHGCSSSimHitcOallocatorlEHGCSSSimHitgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_HGCSSRecoHit;
extern G__linked_taginfo G__dictLN_vectorlEHGCSSRecoHitcOallocatorlEHGCSSRecoHitgRsPgR;
extern G__linked_taginfo G__dictLN_vectorlEHGCSSRecoHitcOallocatorlEHGCSSRecoHitgRsPgRcLcLiterator;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEHGCSSRecoHitcOallocatorlEHGCSSRecoHitgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<HGCSSSimHit,allocator<HGCSSSimHit> > G__vectorlEHGCSSSimHitcOallocatorlEHGCSSSimHitgRsPgR;
typedef vector<HGCSSRecoHit,allocator<HGCSSRecoHit> > G__vectorlEHGCSSRecoHitcOallocatorlEHGCSSRecoHitgRsPgR;
